[Network]
#type rpc or channel
Type="channel"
CAFile="../.keys/bcos/ca.crt"
Cert="../.keys/bcos/sdk.crt"
Key="../.keys/bcos/sdk.key"
[[Network.Connection]]
NodeURL="60.247.61.162:20200"
GroupID=1

[Account]
# only support PEM format for now
KeyFile="../.keys/bcos/accounts_gm/0xf5b0d00f87781fa36f00a8f0ea8e8d4290416659.pem"

[Chain]
ChainID=1
SMCrypto=true
