# iservice config
iservice:
  chain_id: irita-hub
  node_rpc_addr: http://127.0.0.1:26657
  node_grpc_addr: 127.0.0.1:9090
  key_path: .keys/iservice
  key_name: provider
  passphrase: 12345678

# bcos config
bcos:
  config_file: ./store/bcos/config.toml
  store_contract_addr: 0xf5b0d00f87781fa36f00a8f0ea8e8d4290416659
